from pathlib import Path

p = Path("index.html")
s = p.read_text(encoding="utf-8")


def rep(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f"Missing target: {label}")
    s = s.replace(old, new, 1)

# 1) Question screen: media shown immediately + media revealed after answer; remove source button.
rep('''    <div class="question" id="questionText"></div>\n    <div class="image-box" id="imageBox"><img id="questionImage" alt="Obrázek k otázce"></div>\n    <div class="question-actions">\n      <button class="btn good" id="showAnswer">✓ Zobrazit odpověď</button>\n      <button class="btn" id="videoBtn" style="display:none">▶ Video</button>\n      <button class="btn" id="sourceBtn" type="button">🌐 Otevřít obsah</button>\n    </div>\n    <div class="video-box" id="videoBox"><iframe id="videoFrame" title="Video k otázce" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>\n    <div class="answer-box" id="answerBox"><div class="answer-label">Správná odpověď</div><div class="answer" id="answerText"></div><div class="note" id="answerNote"></div></div>''', '''    <div class="question" id="questionText"></div>\n    <div class="image-box" id="imageBox"><img id="questionImage" alt="Obrázek k otázce"></div>\n    <div class="video-box" id="questionVideoBox"><iframe id="questionVideoFrame" title="Video k otázce" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>\n    <div class="question-actions">\n      <button class="btn good" id="showAnswer">✓ Zobrazit odpověď</button>\n    </div>\n    <div class="answer-box" id="answerBox"><div class="answer-label">Správná odpověď</div><div class="answer" id="answerText"></div><div class="note" id="answerNote"></div></div>\n    <div class="question-actions" id="revealMediaActions" style="display:none">\n      <button class="btn" id="revealImageBtn" style="display:none">🖼 Zobrazit obrázek</button>\n      <button class="btn" id="videoBtn" style="display:none">▶ Zobrazit video</button>\n    </div>\n    <div class="image-box" id="revealImageBox"><img id="revealImage" alt="Obrázek po odpovědi"></div>\n    <div class="video-box" id="videoBox"><iframe id="videoFrame" title="Video po odpovědi" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>''', 'question media HTML')

# 2) Keep only one bottom action button.
rep('''    <div class="source-row"><button class="btn good" id="allCorrect">✓ Všem správně</button><button class="btn primary" id="applyAwards">Uložit body → zpět na tabuli</button><button class="btn" id="finishNoScore">Bez bodů → zpět na tabuli</button><button class="btn" id="reopenLater">Nechat otázku aktivní</button></div>''', '''    <div class="source-row"><button class="btn primary" id="applyAwards">Uložit body → zpět na tabuli</button></div>''', 'bottom action buttons')

# 3) Editor heading: keep teacher note, remove source wording.
rep('''<div class="editor-note">Uprav otázku, odpověď, body, poznámku, zdroj nebo video.</div>''', '''<div class="editor-note">Uprav otázku, odpověď, body, poznámku pro učitele, obrázky nebo videa.</div>''', 'editor note')

# 4) Editor fields: keep note; remove source; add immediate/reveal image and video.
rep('''        <div class="editor-field"><label>Poznámka pro učitele</label><textarea class="editor-textarea" data-q-field="note" data-ci="${ci}" data-qi="${qi}">${esc(q.note||"")}</textarea></div>\n        <div class="editor-field"><label>Zdroj – odkaz</label><input class="editor-input" data-q-field="source" data-ci="${ci}" data-qi="${qi}" value="${esc(q.source||"")}" placeholder="https://…"></div>\n        <div class="editor-field"><label>Obrázek – odkaz (volitelné)</label><input class="editor-input" data-q-field="image" data-ci="${ci}" data-qi="${qi}" value="${esc(q.image||"")}" placeholder="Přímá URL obrázku / Google imgres odkaz"><div class="image-help">Nejspolehlivější je v Google Obrázcích zvolit „Kopírovat adresu obrázku“. Odkaz Google imgres s parametrem imgurl aplikace také umí převést.</div></div>\n        <div class="editor-field"><label>Video – odkaz (volitelné)</label><input class="editor-input" data-q-field="video" data-ci="${ci}" data-qi="${qi}" value="${esc(q.video||"")}" placeholder="YouTube / jiný odkaz"></div>''', '''        <div class="editor-field"><label>Poznámka pro učitele</label><textarea class="editor-textarea" data-q-field="note" data-ci="${ci}" data-qi="${qi}">${esc(q.note||"")}</textarea></div>\n        <div class="editor-field"><label>Obrázek u otázky – odkaz (volitelné)</label><input class="editor-input" data-q-field="image" data-ci="${ci}" data-qi="${qi}" value="${esc(q.image||"")}" placeholder="Přímá URL obrázku / Google imgres odkaz"><div class="image-help">Zobrazí se hned s otázkou. Google imgres s parametrem imgurl aplikace umí převést.</div></div>\n        <div class="editor-field"><label>Video u otázky – odkaz (volitelné)</label><input class="editor-input" data-q-field="questionVideo" data-ci="${ci}" data-qi="${qi}" value="${esc(q.questionVideo||"")}" placeholder="YouTube odkaz"><div class="image-help">Zobrazí se hned s otázkou – vhodné třeba pro hádání podle videa.</div></div>\n        <div class="editor-field"><label>Obrázek po odpovědi – odkaz (volitelné)</label><input class="editor-input" data-q-field="revealImage" data-ci="${ci}" data-qi="${qi}" value="${esc(q.revealImage||"")}" placeholder="Přímá URL obrázku / Google imgres odkaz"><div class="image-help">Tlačítko pro obrázek se objeví až po zobrazení správné odpovědi.</div></div>\n        <div class="editor-field"><label>Video po odpovědi – odkaz (volitelné)</label><input class="editor-input" data-q-field="video" data-ci="${ci}" data-qi="${qi}" value="${esc(q.video||"")}" placeholder="YouTube / jiný odkaz"><div class="image-help">Tlačítko pro video se objeví až po zobrazení správné odpovědi.</div></div>''', 'editor media fields')

# 5) Final: keep note, remove source field and source button.
rep('''    <div class="editor-field"><label>Poznámka pro učitele</label><textarea class="editor-textarea" data-final-field="note">${esc(f.note||"")}</textarea></div>\n    <div class="editor-field"><label>Zdroj – odkaz</label><input class="editor-input" data-final-field="source" value="${esc(f.source||"")}" placeholder="https://…"></div>\n    <div class="editor-field"><label>Čas na finále (sekundy)</label>''', '''    <div class="editor-field"><label>Poznámka pro učitele</label><textarea class="editor-textarea" data-final-field="note">${esc(f.note||"")}</textarea></div>\n    <div class="editor-field"><label>Čas na finále (sekundy)</label>''', 'final source editor')
rep('''      <div class="question-actions"><button class="btn good" id="showFinalAnswer">✓ Zobrazit odpověď</button><button class="btn" id="finalSource" type="button">🌐 Otevřít obsah</button></div>''', '''      <div class="question-actions"><button class="btn good" id="showFinalAnswer">✓ Zobrazit odpověď</button></div>''', 'final source button')

# 6) Normalize new media fields while preserving old data compatibility.
rep('''      item.image=String(item.image||"");\n      item.video=String(item.video||"");''', '''      item.image=String(item.image||"");\n      item.questionVideo=String(item.questionVideo||"");\n      item.revealImage=String(item.revealImage||"");\n      item.video=String(item.video||"");''', 'normalize media')

# 7) Blank question schema.
rep('''function makeBlankQuestion(value=100){return {value,question:"",answer:"",note:"",source:"",video:""}}''', '''function makeBlankQuestion(value=100){return {value,question:"",answer:"",note:"",image:"",questionVideo:"",revealImage:"",video:""}}''', 'blank question')

# 8) Question opening/closing logic.
rep('''  $("answerText").textContent=current.q.answer;\n  $("answerNote").textContent=current.q.note||"";\n  $("answerBox").classList.remove("show");\n  $("sourceBtn").dataset.url=current.q.source||""; $("sourceBtn").style.display=current.q.source?"inline-flex":"none";\n  const imgUrl=resolveImageUrl(current.q.image);\n  $("imageBox").classList.toggle("show",!!imgUrl); $("questionImage").src=imgUrl||"";\n  $("videoBtn").style.display=current.q.video?"inline-block":"none";\n  $("videoBox").classList.remove("show"); $("videoFrame").src="";''', '''  $("answerText").textContent=current.q.answer;\n  $("answerNote").textContent=current.q.note||"";\n  $("answerBox").classList.remove("show");\n  const imgUrl=resolveImageUrl(current.q.image);\n  $("imageBox").classList.toggle("show",!!imgUrl); $("questionImage").src=imgUrl||"";\n  const questionVideo=current.q.questionVideo||"";\n  const questionVideoIsYoutube=!!questionVideo&&isYoutubeUrl(questionVideo);\n  $("questionVideoBox").classList.toggle("show",questionVideoIsYoutube);\n  $("questionVideoFrame").src=questionVideoIsYoutube?youtubeEmbed(questionVideo):"";\n  $("revealMediaActions").style.display="none";\n  $("revealImageBtn").style.display="none";\n  $("videoBtn").style.display="none";\n  $("revealImageBox").classList.remove("show"); $("revealImage").src="";\n  $("videoBox").classList.remove("show"); $("videoFrame").src="";''', 'open question media')
rep('''  $("questionOverlay").classList.remove("show");\n  $("videoFrame").src=""; $("questionImage").src=""; $("imageBox").classList.remove("show"); render(); current=null; pendingAwards={};''', '''  $("questionOverlay").classList.remove("show");\n  $("videoFrame").src=""; $("questionVideoFrame").src="";\n  $("questionImage").src=""; $("revealImage").src="";\n  $("imageBox").classList.remove("show"); $("questionVideoBox").classList.remove("show"); $("revealImageBox").classList.remove("show"); $("videoBox").classList.remove("show");\n  render(); current=null; pendingAwards={};''', 'close question media')

# 9) Reset wording: teacher note remains; sources are no longer part of editor.
rep('''if(!confirm("Vrátit celý obsah otázek, odpovědí, poznámek a zdrojů do původní verze?"))return;''', '''if(!confirm("Vrátit celý obsah otázek, odpovědí, poznámek a médií do původní verze?"))return;''', 'reset wording')

# 10) Final show logic no longer accesses removed finalSource element.
rep('''  $("finalCategory").textContent=QUIZ_DATA.final.category;$("finalQuestion").textContent=QUIZ_DATA.final.question;$("finalAnswer").textContent=QUIZ_DATA.final.answer;$("finalNote").textContent=QUIZ_DATA.final.note||"";$("finalAnswerBox").classList.remove("show");$("finalSource").dataset.url=QUIZ_DATA.final.source||"";$("finalSource").style.display=QUIZ_DATA.final.source?"inline-flex":"none";''', '''  $("finalCategory").textContent=QUIZ_DATA.final.category;$("finalQuestion").textContent=QUIZ_DATA.final.question;$("finalAnswer").textContent=QUIZ_DATA.final.answer;$("finalNote").textContent=QUIZ_DATA.final.note||"";$("finalAnswerBox").classList.remove("show");''', 'final source logic')

# 11) Event handlers: one bottom button only; reveal media only becomes available after answer.
rep('''$("closeQuestion").onclick=()=>closeQuestion(true);$("allCorrect").onclick=selectAllCorrect;$("applyAwards").onclick=applyAwardsAndClose;$("finishNoScore").onclick=()=>closeQuestion(true);$("reopenLater").onclick=()=>closeQuestion(false);\n$("showAnswer").onclick=()=>$("answerBox").classList.add("show");\n$("questionImage").onerror=()=>{if($("questionImage").src){$("imageBox").classList.remove("show");toast("Obrázek se nepodařilo načíst – zkus přímou adresu obrázku")}};\n$("sourceBtn").onclick=()=>openContentView(current?.q?.source,"Zdroj k otázce");\n$("contentBack").onclick=closeContentView;\n$("contentExternal").onclick=()=>{if(!activeContentUrl)return;const w=window.open(activeContentUrl,"_blank","noopener,noreferrer");if(!w)toast("Prohlížeč zablokoval nový panel – povol vyskakovací okna")};\n$("videoBtn").onclick=()=>{if(!current?.q?.video)return;if(!isYoutubeUrl(current.q.video)){openContentView(current.q.video,"Video k otázce");return}const box=$("videoBox");const show=!box.classList.contains("show");box.classList.toggle("show",show);$("videoFrame").src=show?youtubeEmbed(current.q.video):""};''', '''$("closeQuestion").onclick=()=>closeQuestion(true);$("applyAwards").onclick=applyAwardsAndClose;\n$("showAnswer").onclick=()=>{\n  $("answerBox").classList.add("show");\n  const hasImage=!!current?.q?.revealImage,hasVideo=!!current?.q?.video;\n  $("revealMediaActions").style.display=(hasImage||hasVideo)?"flex":"none";\n  $("revealImageBtn").style.display=hasImage?"inline-block":"none";\n  $("videoBtn").style.display=hasVideo?"inline-block":"none";\n};\n$("questionImage").onerror=()=>{if($("questionImage").src){$("imageBox").classList.remove("show");toast("Obrázek se nepodařilo načíst – zkus přímou adresu obrázku")}};\n$("revealImage").onerror=()=>{if($("revealImage").src){$("revealImageBox").classList.remove("show");toast("Obrázek se nepodařilo načíst – zkus přímou adresu obrázku")}};\n$("revealImageBtn").onclick=()=>{if(!current?.q?.revealImage)return;const box=$("revealImageBox");const show=!box.classList.contains("show");box.classList.toggle("show",show);$("revealImage").src=show?resolveImageUrl(current.q.revealImage):""};\n$("contentBack").onclick=closeContentView;\n$("contentExternal").onclick=()=>{if(!activeContentUrl)return;const w=window.open(activeContentUrl,"_blank","noopener,noreferrer");if(!w)toast("Prohlížeč zablokoval nový panel – povol vyskakovací okna")};\n$("videoBtn").onclick=()=>{if(!current?.q?.video)return;if(!isYoutubeUrl(current.q.video)){openContentView(current.q.video,"Video k otázce");return}const box=$("videoBox");const show=!box.classList.contains("show");box.classList.toggle("show",show);$("videoFrame").src=show?youtubeEmbed(current.q.video):""};''', 'question event handlers')

# 12) Remove final source handler.
rep('''$("finalBtn").onclick=openFinal;$("closeFinal").onclick=()=>{stopFinalTimer();$("finalOverlay").classList.remove("show")};$("showFinalQuestion").onclick=showFinal;$("showFinalAnswer").onclick=()=>$("finalAnswerBox").classList.add("show");$("finalSource").onclick=()=>openContentView(QUIZ_DATA.final.source,"Zdroj finále");$("finalTimerStart").onclick=startFinalTimer;''', '''$("finalBtn").onclick=openFinal;$("closeFinal").onclick=()=>{stopFinalTimer();$("finalOverlay").classList.remove("show")};$("showFinalQuestion").onclick=showFinal;$("showFinalAnswer").onclick=()=>$("finalAnswerBox").classList.add("show");$("finalTimerStart").onclick=startFinalTimer;''', 'final source handler')

p.write_text(s, encoding="utf-8")
